name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: petcare-main
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
        working-directory: petcare-main
      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: petcare-main
      - name: Type-check
        run: npx tsc --noEmit
        working-directory: petcare-main
      - name: Lint
        run: npx next lint
        working-directory: petcare-main
      - name: Build
        run: npm run build
        working-directory: petcare-main
